### ISSUE TITLE
FocusRequester is not initialized

### ISSUE THREAD

**Issue by mathieuisabel** [vaticle/typedb-studio#548] opened 2022-05-27 18:38 UTC
Please replace every line in curly brackets ( { like this } ) with appropriate answers, and remove this line.

## Description

{ Please provide a clear and concise description of the bug. }

## Environment

1. TypeDB version: 2.10
2. OS of TypeDB server: Windows 11
3. Studio version: 2.10
4. OS of Studio:  Windows 11
5. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:

1. Connect to db
2. Browse relations in type tree

## Expected Output

No crash

## Additional information

My CPU was maxed out at that moment as I was loading data with typedb-loader.

## Actual Output

Error thrown:

Title: 
   FocusRequester is not initialized. Here are some possible fixes:

   1. Remember the FocusRequester: val focusRequester = remember { FocusRequester() }
   3. Did you forget to add a Modifier.focusRequester() ?
   4. Are you attempting to request focus during composition? Focus requests should be made in
   response to some event. Eg Modifier.clickable { focusRequester.requestFocus() }

Trace: java.lang.IllegalStateException: 
   FocusRequester is not initialized. Here are some possible fixes:

   1. Remember the FocusRequester: val focusRequester = remember { FocusRequester() }
   2. Did you forget to add a Modifier.focusRequester() ?
   3. Are you attempting to request focus during composition? Focus requests should be made in
   response to some event. Eg Modifier.clickable { focusRequester.requestFocus() }

	at androidx.compose.ui.focus.FocusRequester.requestFocus(FocusRequester.kt:54)
	at com.vaticle.typedb.studio.view.common.component.Navigator$onPointerInput$2.invoke(Navigator.kt:511)
	at com.vaticle.typedb.studio.view.common.component.Navigator$onPointerInput$2.invoke(Navigator.kt:509)
	at com.vaticle.typedb.studio.view.common.component.ContextMenu$State$onPointerInput$6$1.invokeSuspend(ContextMenu.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:529)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.dispatchPointerEvent(SuspendingPointerInputFilter.kt:422)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:435)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:285)
	at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:152)
	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:89)
	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:80)
	at androidx.compose.ui.platform.SkiaBasedOwner.processPointerInput-gBdvCQM$ui(SkiaBasedOwner.skiko.kt:343)
	at androidx.compose.ui.platform.SkiaBasedOwner.processPointerInput-gBdvCQM$ui$default(SkiaBasedOwner.skiko.kt:341)
	at androidx.compose.ui.ComposeScene.onMousePressed(ComposeScene.skiko.kt:444)
	at androidx.compose.ui.ComposeScene.sendPointerEvent-Kr8mkKM(ComposeScene.skiko.kt:426)
	at androidx.compose.ui.ComposeScene.sendPointerEvent-Kr8mkKM$default(ComposeScene.skiko.kt:397)
	at androidx.compose.ui.awt.ComposeLayer_desktopKt.onMouseEvent(ComposeLayer.desktop.kt:420)
	at androidx.compose.ui.awt.ComposeLayer_desktopKt.access$onMouseEvent(ComposeLayer.desktop.kt:1)
	at androidx.compose.ui.awt.ComposeLayer$onMouseEvent$1.invoke(ComposeLayer.desktop.kt:278)
	at androidx.compose.ui.awt.ComposeLayer$onMouseEvent$1.invoke(ComposeLayer.desktop.kt:274)
	at androidx.compose.ui.awt.ComposeLayer.catchExceptions(ComposeLayer.desktop.kt:89)
	at androidx.compose.ui.awt.ComposeLayer.onMouseEvent(ComposeLayer.desktop.kt:274)
	at androidx.compose.ui.awt.ComposeLayer.access$onMouseEvent(ComposeLayer.desktop.kt:70)
	at androidx.compose.ui.awt.ComposeLayer$3.mousePressed(ComposeLayer.desktop.kt:254)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

**Comment by alexjpwalker** [comment] 2022-05-30 10:44
Hi @mathieuisabel . I believe is this is a known bug in version `2.10.0-alpha` that was fixed in `2.10.0-alpha-2`:

> **Type Browser**
> 
> - Fix error when performing keyboard input with a Type selected

(source: https://github.com/vaticle/typedb-studio/releases/tag/2.10.0-alpha-2)

Could you confirm your precise Studio version, and try upgrading if you don't have the most recent one?

**Comment by mathieuisabel** [comment] 2022-06-02 16:46
The build version doesn't seem to be reflected entirely when I look at this but I encountered the issue again today.

![image](https://user-images.githubusercontent.com/15805484/171681917-422ba7c7-e0ec-4356-8c20-c9ba3cb26bc8.png)

**Comment by jamesreprise** [comment] 2022-08-30 13:57
Hi @mathieuisabel, are you still experiencing this issue?

I haven't been able to replicate it locally, even while pushing my CPU to maximum on every thread. 

Could you verify if you're still having the same problem on Studio 2.11?

Many thanks.

**Comment by jamesreprise** [comment] 2022-10-25 14:22
Closing this as we've been unable to reproduce the issue since bug fix was released.

**Closed by jamesreprise** 2022-10-25 14:22 UTC
Labels: type: bug, priority: high, domain: types
