### ISSUE TITLE
embed console for easier round-trip development

### ISSUE THREAD

**Issue by grexe** [vaticle/typedb-studio#337] opened 2020-08-10 15:53 UTC
## Problem to Solve

Currently, developing a schema from Grakn workbase via UI is quite limited, slow and cumbersome.
I'd like to have the full power of Grakn console from within the cosy UI environment of the Grakn workable, so I can develop my schema like a pro, but see the results in near realtime (so it should be like a live connection and visualise my schema immediately, at least as much as possible).

## Current Workaround

Very tedious process like in the old C/C++ times, writing code by hand in the blind (ideally with support from the VSCode Graql plugin), deploying to the server, then see if I am happy with it and repeat the procedure until I am.

## Proposed Solution

Provide a deep and near-realtime connection between an embedded Grakn console and the Grakn workbase, allowing me to develop a schema like code, but see it at the same time as as knowledge graph.
Changes are propagated in both directions, and when I select an element in code or the graph, the other end is highlighted automatically.

**Comment by alexjpwalker** [comment] 2021-11-02 17:50
Thanks for the report! This issue is a duplicate of:
- #241 

Studio has replaced Workbase. We are not planning to embed Console into Studio, but we are planning to support all query types, which means it can be used just like Console: see:
- #438

**Closed by alexjpwalker** 2021-11-02 17:50 UTC
