### ISSUE TITLE
Visualization is not giving expected output

### ISSUE THREAD

**Issue by SkylarACD** [vaticle/typedb-studio#358] opened 2021-01-15 18:23 UTC
## Description

(I am following this tutorial: https://dev.grakn.ai/docs/examples/phone-calls-queries?tab=python . When I enter the provided query, the visualization is incomplete.)

## Environment

1. Grakn version: (Grakn Core Mac 1.8.1)
2. OS of Grakn server: (Mac OS 10)
3. Workbase version: (1.3.6)
4. OS of Workbase: (Mac OS 10)
5. Other environment details: 

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. (I'm not sure how far back to go with this. Follow this tutorial to model and load the phone_calls schema into grakn: https://dev.grakn.ai/docs/examples/phone-calls-queries?tab=python )
2. (In Grakn Workbase, query: 
match
  $customer isa person, has phone-number $phone-number;
  $company isa company, has name "Telecom";
  (customer: $customer, provider: $company) isa contract;
  $target isa person, has phone-number "+86 921 547 9004";
  (caller: $customer, callee: $target) isa call, has started-at $started-at;
  $min-date == 2018-09-14T17:18:49; $started-at > $min-date;
get $phone-number;) 

## Expected Output

(Here is the expected output from the tutorial: 
![image](https://user-images.githubusercontent.com/71157379/104763580-beb9f400-572b-11eb-9456-f2c82d78a1f3.png)
)

## Actual Output

(Here is the actual output from Grakn Workbase:

![Screen Shot 2021-01-15 at 12 19 13 PM](https://user-images.githubusercontent.com/71157379/104763715-ef9a2900-572b-11eb-92db-13cba3ef7a6a.png)
)
 
## Additional information
(thank you)

**Comment by alexjpwalker** [comment] 2021-05-18 11:23
The query in your screenshot does not match the query in the example. You have `get $phone-number`; the example gets `$customer, $company, $call, $contract ...`

**Comment by alexjpwalker** [comment] 2021-11-02 15:17
I will close this issue as it appears to be caused by a typo. Feel free to reopen if the issue is still relevant.

**Closed by alexjpwalker** 2021-11-02 15:17 UTC
