### ISSUE TITLE
Unexpected and non-deterministic output: missing edges

### ISSUE THREAD

**Issue by bfour** [vaticle/typedb-studio#524] opened 2021-12-19 00:22 UTC
_**Issue**_
Multiple runs of the following query
```
match $x isa item, has id $id, has creationTime $creationTime, has lastChangeTime $lastChangeTime, has title $title, has description $description, has quantity $quantity, has mainImage $mainImage;

$container isa item;
$receiver isa item;
$loc (provider: $container, receiver: $receiver) isa location;

get $x, $id, $title, $loc;
```

sometimes returned attributes that were not attached to their corresponding entity. Which attribute was dangling was random (sometimes from entity "UUID2", sometimes entity "UUID4" etc).

Sometimes the output was as expected. 

Run 1 - faulty
![image](https://user-images.githubusercontent.com/1163867/146659023-40751d7b-d2ca-45cb-b87f-cb47c49b312b.png)

Run 2 - ok
![image](https://user-images.githubusercontent.com/1163867/146659036-fd2dd9ce-582c-4b97-b2aa-ce0c04ff62a2.png)

Run 3 - faulty
![image](https://user-images.githubusercontent.com/1163867/146659041-50115828-4d4b-4d0b-9261-710be882c967.png)

Run 4 - ok
![image](https://user-images.githubusercontent.com/1163867/146659044-eaea6574-87f5-436a-901c-a592ec1a7c35.png)

Run 5 - faulty
![image](https://user-images.githubusercontent.com/1163867/146659052-2ccb12d8-3d55-4bac-bc5c-0adc6821cb10.png)

Run 6 - faulty
![image](https://user-images.githubusercontent.com/1163867/146659054-5e867cbc-03cb-4e28-baf6-958a3cd8fb71.png)

No other process was (supposed to be) manipulating data concurrently.

_**Expected behaviour**_
Output visualization should show graph with attributes attached to entity-node.

**_Environment_**
TypeDBServer 2.5.0
Windows 10
TypeDB Studio 2.4.0

_**Schema**_
```
define

id sub attribute,
    value string;

creationTime sub attribute,
    value long;

lastChangeTime sub attribute,
    value long;

title sub attribute,
    value string;

description sub attribute,
    value string;

mainImage sub attribute,
    value string;

quantity sub attribute,
    value long;

customEntity sub entity, 
  owns id @key,
  owns creationTime,
  owns lastChangeTime;

item sub customEntity,
  owns title,
  owns description,
  owns mainImage,
  owns quantity,
  plays location:provider,
  plays location:receiver
;

define

location sub relation,
  relates provider,
  relates receiver;
```

**Comment by alexjpwalker** [comment] 2021-12-20 11:35
Thanks for the report!

**Comment by alexjpwalker** [comment] 2022-05-27 13:12
![image](https://user-images.githubusercontent.com/14253102/170514974-96024295-e685-47cd-91fd-df3153dc0e38.png)

In the attached screenshot, the "name: Restrict ..." should be owned by the `intrusion-set`, but an edge has not been drawn between them.

I suspect this means there is a bug where `EdgeCandidate`s are not being correctly completed, or are getting dropped too soon.

**Comment by haikalpribadi** [comment] 2022-05-29 15:03
I can also reproduce this bug easily with a small dataset, @alexjpwalker : 

![detached attributes](https://user-images.githubusercontent.com/567679/170876273-be854b77-050f-4c7b-b05d-e51f0ca659ca.png)

I can given you the dataset privately.

**Comment by alexjpwalker** [comment] 2022-06-06 15:19
To confirm, this issue affects not only attributes, but also potentially other edge types.

- #551

**Comment by alexjpwalker** [comment] 2022-06-07 11:14
Fixed by https://github.com/vaticle/typedb-studio/commit/9ccc1349074305b9151eda7a115da2689e86e2ba

**Closed by alexjpwalker** 2022-06-07 11:14 UTC
Labels: type: bug, priority: blocker

**Comment by mathieuisabel** [comment] 2022-06-27 20:05
@alexjpwalker FYI I noticed this afternoon another possible occurrence of this issue in studio 2.10-alpha-10. 

If I execute multiple query in the same run and one of them is bad, it gives something like this:

![image](https://user-images.githubusercontent.com/15805484/176026256-2fa4d78f-cbee-41ca-9942-d89ca2bb3f2c.png)

In this example, the first query is ok, the second is bad and the third is  good as well. Only the first one is partially shown.

**Comment by haikalpribadi** [comment] 2022-06-27 20:35
I think the answer is in the error message in the bottom right, @mathieuisabel . Your second line `match $derp isa derp;` caused the transaction to close and resulted in an incomplete graph.

**Comment by mathieuisabel** [comment] 2022-06-28 13:12
@haikalpribadi If I run the first query only it renders fine under the Graph 1 tab:

![image](https://user-images.githubusercontent.com/15805484/176186593-297648ae-d9e6-470d-b2a6-ce7134fc6fc0.png)

Same for the last query:

![image](https://user-images.githubusercontent.com/15805484/176186695-e3379c42-a8bd-43a9-8ca3-84474fa51486.png)

The middle garbage query is throwing the error (which is ok, that's the repro):

![image](https://user-images.githubusercontent.com/15805484/176186834-d7eba87e-b55b-40f2-8ed8-bf1a115f15ee.png)

So a few points from that:

- Query 1 should render correctly with all edges
- Query 3 should render

So I should see Graph 1 and Graph 2 tabs for the two working queries. For Query 2 (bad query) it might be good to have a clearer way to see it failed specifically.

Let me know if that clarifies.

**Comment by alexjpwalker** [comment] 2022-06-29 10:24
This is the expected behaviour, because when an error occurs in a transaction, the transaction closes - meaning that any graphs that are in the process of loading will stop loading and may be incomplete.

What I think what we need here is a message displayed somewhere visible from all output tabs, saying "The transaction was closed early due to an error. Results and graphs may be incomplete."

**Comment by alexjpwalker** [comment] 2022-06-29 12:59
> The error is returned and no results are coming back, which I think is probably cleaner than returning partial results to respect the full transaction

Right. TypeDB doesn't currently have a concept of batching in the same way that Microsoft SQL does. (It's worth noting that `GO` is a special construct of SQL Server Management Studio, and is neither part of the SQL standard, nor the T-SQL standard: see https://stackoverflow.com/a/2299280/2902555)

So this certainly does seem like an advanced feature, and we would need to know the full scope of the feature (how it works as a concept), and not just what effects it has (e.g: reporting semantic errors before running any query within the batch)

**Comment by mathieuisabel** [comment] 2022-06-29 13:16
Yes, GO is simply a way to explicitly delimit each query batch in sqlcmd/SSMS. In the programming world, they have something called Multiple Active Result Set. See: https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/multiple-active-result-sets-mars

Basically, you can send multiple batches on the same connection.

Coming back to the typedb world, I would still recommend failing the whole batch with the error instead of the incomplete/incorrect result of the first query if we go with the idea that something in the batch is bad. Otherwise, might as well treat each match statement as individual batches and have the ones that are ok render properly.

**Comment by alexjpwalker** [comment] 2022-06-29 13:52
Doing some further research, it appears that `GO` is conceptually equivalent to a command batch delimiter. When executing a query of the form
```
x()
y()
GO
z()
```
this says:
- Send `x(); y();` to the server and collect the results in full
- Then, send `z()` to the server and collect the results in full

Looking at the implementation of TypeDB Studio's `QueryRunner` in fact shows that each `match` query (and indeed, each distinct query) **is** actually run as its own batch. We wait for the answers to be returned fully from Query 1 before sending Query 2 to the server.

The discrepancy, then, originates from the additional work that the Graph Visualiser has to do in order to load edges. Because the query itself only returns Concepts in a `Map` structure, with no information about the edges (connections between those concepts), we do additional work in the same Transaction but which is outside the scope of the query.

Perhaps it would make sense to scope that work to the query, so that the query is only considered "done" once all the graph edges have been loaded.
